// <auto-generated />
using System;
using DeveMobileLPR.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DeveMobileLPR.Storage.Migrations
{
    [DbContext(typeof(LprDbContext))]
    [Migration("20260804010000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.SightingModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BodyType")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_type");

                    b.Property<decimal?>("CatalogPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("catalog_price");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("DisplayPlate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_plate");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("FuelDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("fuel_description");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<float?>("LocationAccuracyMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("location_accuracy_meters");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_plate");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_count");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<int?>("RegistrationYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("registration_year");

                    b.Property<string>("SnapshotReference")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_reference");

                    b.Property<long?>("TripId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("CatalogPrice")
                        .IsDescending(true)
                        .HasDatabaseName("ix_sightings_price")
                        .HasFilter("\"catalog_price\" IS NOT NULL");

                    b.HasIndex("NormalizedPlate", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sightings_plate_last_seen");

                    b.HasIndex("TripId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sightings_trip_last_seen");

                    b.ToTable("sightings");
                });

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.TripModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("distance_meters");

                    b.Property<float?>("EndAccuracyMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("end_accuracy_meters");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("end_latitude");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("end_longitude");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<float?>("StartAccuracyMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("start_accuracy_meters");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("start_latitude");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("start_longitude");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending(true)
                        .HasDatabaseName("ix_trips_started");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.TripPointModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<float?>("AccuracyMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("accuracy_meters");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<long>("TripId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "RecordedAt")
                        .HasDatabaseName("ix_trip_points_trip_time");

                    b.ToTable("trip_points");
                });

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.SightingModel", b =>
                {
                    b.HasOne("DeveMobileLPR.Storage.Models.TripModel", "Trip")
                        .WithMany("Sightings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.TripPointModel", b =>
                {
                    b.HasOne("DeveMobileLPR.Storage.Models.TripModel", "Trip")
                        .WithMany("Points")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DeveMobileLPR.Storage.Models.TripModel", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
