<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DeveMobileLPR</RootNamespace>
    <AssemblyName>DeveMobileLPR.Inference</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DeveMobileLPR.Core/DeveMobileLPR.Core.csproj" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
  </ItemGroup>
</Project>
