<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DeveMobileLPR</RootNamespace>
    <AssemblyName>DeveMobileLPR.Storage</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DeveMobileLPR.Core/DeveMobileLPR.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
</Project>
